using System;
using pnyx.net.errors;

namespace pnyx.net.util.dates;

public class DateRange
{
    public LocalRangeEnum type { get; set; }       
    public DateTime? startDate { get; set; }
    public DateTime? endDate { get; set; }
    
    public LocalRange toLocalRange(LocalDay today)
    {
        LocalDay? startLocal = today.withTimeZoneNullable(startDate);
        LocalDay? endLocal = today.withTimeZoneNullable(endDate);
        return LocalRange.build(type, today, startLocal, endLocal);
    }
    
    public static implicit operator DateRange(LocalRangeEnum type)
    {
        return new DateRange { type = type }; 
    }
    
    public static explicit operator DateRange(string valueAsText)
    {
        return parse(valueAsText) ?? throw new ParseException("Empty strings cannot be converted to a DateRange");
    }
    
    public override string ToString()
    {
        string typeAsText = ((int)type).ToString();
        
        // Strictly a type
        if (startDate == null && endDate == null)
            return typeAsText;
        
        // A type and startDate
        if (endDate == null)
            return $"{typeAsText}|{startDate?.toIso8601Date()}";
        
        // A type and endDate (start optional)
        return $"{typeAsText}|{startDate?.toIso8601Date()}|{endDate?.toIso8601Date()}";
    }

    /// <summary>
    /// Parsing a string that represents a date range, suitable for URL bindings. String is in the format
    /// generated by the ToString method.
    ///
    /// Examples:
    ///     30
    ///     90|2023-01-01
    ///     93|2023-01-01|2025-01-01
    /// </summary>
    /// <param name="text">String that represents a date range, suitable for URL bindings</param>
    /// <returns>Parsed date range or null</returns>
    /// <exception cref="ParseException"></exception>
    public static DateRange? parse(string? text)
    {
        if (String.IsNullOrEmpty(text))
            return null;

        string[] parts = text.Split('|');
        if (parts.Length != 1 && parts.Length != 2 && parts.Length != 3)
            throw new ParseException($"Invalid number of parts={parts.Length} for DateRange value={text}");
        
        LocalRangeEnum type = (LocalRangeEnum)int.Parse(parts[0]);
        if (!EnumUtil.isValid(type))
            throw new ParseException($"Invalid type={type} for DateRange value={text}");
        
        if (parts.Length == 1)
            return new DateRange { type = type };

        string startPart = parts[1];
        string endPart = parts.Length == 3 ? parts[2] : "";
        
        DateTime? startDate = null;
        DateTime? endDate = null;
        try
        {
            if (!string.IsNullOrEmpty(startPart)) startDate = DateUtil.parseIso8601Date(startPart);
            if (!string.IsNullOrEmpty(endPart)) endDate = DateUtil.parseIso8601Date(endPart);
        }
        catch (FormatException e)
        {
            throw new ParseException(e.Message, e);
        }
        
        return new DateRange
        {
            type = type,
            startDate = startDate,
            endDate = endDate
        };
    }
}